android.useAndroidX=true
android.enableJetifier=true

# Gradle
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx6g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=false
org.gradle.configureondemand=false

# Kotlin
kotlin.incremental=false
kotlin.daemon.jvmargs=-Xmx2g
systemProp.kotlin.statistics.enabled=true

# Android
android.experimental.enableBuildConfigGeneration=true

org.gradle.java.home=/Users/saeedmostafa/Library/Java/JavaVirtualMachines/jbr-17.0.8.1/Contents/Home
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false