package com.inspection.model

/**
 * Created by saeedmostafa on 2/1/18.
 */

class CsiFacility {
    var groupinaccount = ""
    var webaddress = ""
    var alertstoowner = ""
    var applicant = ""
    var nat_facnum = ""
    var aaaappton = ""
    var valueaddedjoindate = ""
    var wavname = ""
    var numberoftechs = ""
    var directorid = ""
    var managerlast = ""
    var owneremail = ""
    var active = ""
    var ownerid = ""
    var managerfirst = ""
    var officeid = ""
    var clientfacnum = ""
    var installer = ""
    var email4 = ""
    var email5 = ""
    var email2 = ""
    var email3 = ""
    var email1 = ""
    var city = ""
    var shopfax = ""
    var acnm = ""
    var numberofpcs = ""
    var zip = ""
    var cor0369filter = ""
    var facname = ""
    var adminid = ""
    var contactemail = ""
    var zipcode = ""
    var id = ""
    var specialistid = ""
    var club = ""
    var state = ""
    var status = ""
    var manageremail = ""
    var ownerlast = ""
    var ownername = ""
    var nat_clubcode = ""
    var joindate = ""
    var installdatetarget = ""
    var applicantexceedlimit = ""
    var aaastate = ""
    var rnum = ""
    var valueadded = ""
    var website = ""
    var fax = ""
    var phone1 = ""
    var phone2 = ""
    var address1 = ""
    var address2 = ""
    var ownerfirst = ""
    var clientaaanat_nat = ""
    var admin2id = ""
    var numberpcs = ""
    var sendreports = ""
    var facnum = ""
    var customerdatestartfrom = ""
    var managergender = ""
    var dateshopopened = ""
    var clubcode = ""
    var numberofbays = ""
    var contactlast = ""
    var avemonthro = ""
    var numemps = ""
    var apptsetupreminder = ""
    var notes = ""
    var shopmanagmentsys = ""
    var shopphone = ""
    var sendalerts = ""
    var squarefootage = ""
    var ownergender = ""
    var contactfirst = ""
    var managername = ""
    var alertstomanager = ""
    var typeofshop = ""
    var haswebsite = ""
}