package com.inspection.model

class VisitationsModel {

    var pendingVisitationsArray = ArrayList<PendingVisitationModel>()
    var completedVisitationsArray = ArrayList<CompletedVisitationModel>()
    var deficienciesArray = ArrayList<DeficiencyModel>()


    class PendingVisitationModel{
        var FacID = ""
        var ClubCode = ""
        var FACNo = ""
        var BusinessName = ""
        var BusTypeID = ""
        var EntityName = ""
        var assignedToID = ""
        var officeID = ""
        var TaxIDNumber = ""
        var FacilityRepairOrderCount = ""
        var FacilityAnnualInspectionMonth = ""
        var InspectionCycle = ""
        var TimezoneID = ""
        var SvcAvailability = ""
        var FacilityTypeID = ""
        var AutomotiveRepairNumber = ""
        var AutomotiveRepairExpDate = ""
        var ContractCurrentDate = ""
        var ContractInitialDate = ""
        var BillingMonth = ""
        var BillingAmount = ""
        var InternetAccess = ""
        var WebSite = ""
        var TerminationDate = ""
        var TerminationID = ""
        var TerminationComments = ""
        var insertBy = ""
        var insertDate = ""
        var updateBy = ""
        var updateDate = ""
        var active = ""
        var ACHParticipant = ""
        var InsuranceExpDate = ""
        var ContractTypeID = ""
    }

    class CompletedVisitationModel{
        var FacID = ""
        var ClubCode = ""
        var FACNo = ""
        var BusinessName = ""
        var BusTypeID = ""
        var EntityName = ""
        var assignedToID = ""
        var officeID = ""
        var TaxIDNumber = ""
        var FacilityRepairOrderCount = ""
        var FacilityAnnualInspectionMonth = ""
        var InspectionCycle = ""
        var TimezoneID = ""
        var SvcAvailability = ""
        var FacilityTypeID = ""
        var AutomotiveRepairNumber = ""
        var AutomotiveRepairExpDate = ""
        var ContractCurrentDate = ""
        var ContractInitialDate = ""
        var BillingMonth = ""
        var BillingAmount = ""
        var InternetAccess = ""
        var WebSite = ""
        var TerminationDate = ""
        var TerminationID = ""
        var TerminationComments = ""
        var insertBy = ""
        var insertDate = ""
        var updateBy = ""
        var updateDate = ""
        var active = ""
        var ACHParticipant = ""
        var InsuranceExpDate = ""
        var ContractTypeID = ""
        var FACID1 = ""
        var visitationID = ""
        var DatePerformed = ""
        var DateReceived = ""
    }

    class DeficiencyModel {
        var FacID = ""
        var ClubCode = ""
        var FACNo = ""
        var BusinessName = ""
        var BusTypeID = ""
        var EntityName = ""
        var assignedToID = ""
        var officeID = ""
        var TaxIDNumber = ""
        var FacilityRepairOrderCount = ""
        var FacilityAnnualInspectionMonth = ""
        var InspectionCycle = ""
        var TimezoneID = ""
        var SvcAvailability = ""
        var FacilityTypeID = ""
        var AutomotiveRepairNumber = ""
        var AutomotiveRepairExpDate = ""
        var ContractCurrentDate = ""
        var ContractInitialDate = ""
        var BillingMonth = ""
        var BillingAmount = ""
        var InternetAccess = ""
        var WebSite = ""
        var TerminationDate = ""
        var TerminationID = ""
        var TerminationComments = ""
        var insertBy = ""
        var insertDate = ""
        var updateBy = ""
        var updateDate = ""
        var active = ""
        var ACHParticipant = ""
        var InsuranceExpDate = ""
        var ContractTypeID = ""
        var FACID1 = ""
        var DefID = ""
        var DefTypeID = ""
        var DeficiencyName = ""
        var VisitationDate = ""
        var EnteredDate = ""
        var Comments = ""
        var insertBy1 = ""
        var insertDate1 = ""
        var updateBy1 = ""
        var updateDate1 = ""
        var DueDate = ""
    }


}